name: Deploy Prod
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: waiuru-prod
  USE_GKE_GCLOUD_AUTH_PLUGIN: true
  IMAGE: waiuru-site

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - run: npm run build

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Build
        run: |-
          docker build \
            -t "gcr.io/$PROJECT_ID/prod/$IMAGE:$GITHUB_SHA" \
            -t "gcr.io/$PROJECT_ID/prod/$IMAGE:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/prod/$IMAGE:$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/prod/$IMAGE:latest"

      - name: Generate GCR image path
        shell: bash
        run: echo "path=$(echo gcr.io/$PROJECT_ID/prod/$IMAGE:$GITHUB_SHA)" >>$GITHUB_OUTPUT
        id: image_path

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: prod-waiuru-site
          image: ${{ steps.image_path.outputs.path }}
          flags: --allow-unauthenticated

      - name: Use output
        run: curl "${{ steps.deploy.outputs.url }}"
